name: Tests
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Node.js
    runs-on: node:lts-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Puppeteer prerequisites
        run: apk update && apk add --no-cache nmap && \
          echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
          echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
          apk update && \
          apk add --no-cache \
            chromium \
            harfbuzz \
            "freetype>2.8" \
            ttf-freefont \
            nss
      - name: Run All Node.js Tests in Docker
        environment:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: yarn \
          yarn samples