name: Tests
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run All Node.js Tests in Docker
        run: docker-compose up --build -d -f docker-compose.samples.yml